# Generated by Django 3.2.25 on 2024-06-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customermodel_documentsetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex'), ('MtF Female', 'MtF Female'), ('FtM Male', 'FtM Male')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
    ]
