# Generated by Django 3.2.25 on 2024-06-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240609_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to='document/%Y/%M/')),
                ('extracted_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customermodel')),
            ],
        ),
    ]
