# Generated by Django 3.2.25 on 2024-06-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customerdocumentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocumentmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customermodel'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex'), ('MtF Female', 'MtF Female'), ('FtM Male', 'FtM Male')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='surname',
            field=models.CharField(blank=True, choices=[('mr.', 'MR.'), ('mrs.', 'Mrs')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentsetmodel',
            name='ocr_Labels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
